// VCart Products Database - 32 Products with image keywords

const ProductsDB = [
  { id: 1, name: 'Wireless Bluetooth Noise Cancelling Headphones', category: 'Electronics', price: 2499, originalPrice: 4999, rating: 4.5, reviews: 2345, badge: 'Hot', img: 'headphone', featured: true, trending: true, bestseller: true, flashdeal: false, desc: 'Premium wireless headphones with active noise cancellation, 30-hour battery life, and crystal-clear audio. Over-ear design with memory foam cushions for all-day comfort.', specs: { Brand: 'SoundMax', 'Driver': '40mm', Battery: '30 hours', Bluetooth: '5.3' } },
  { id: 2, name: 'Smart Fitness Tracker with Heart Rate Monitor', category: 'Electronics', price: 3999, originalPrice: 7999, rating: 4.3, reviews: 1876, badge: 'Sale', img: 'fitness-tracker', featured: true, trending: true, bestseller: false, flashdeal: true, desc: 'Advanced fitness tracker with 24/7 heart rate monitoring, SpO2 sensor, built-in GPS, and 14-day battery life. Water-resistant to 50 meters.', specs: { Brand: 'FitPro', Display: '1.4" AMOLED', Battery: '14 days', 'Water': '5 ATM' } },
  { id: 3, name: 'Premium Leather Wallet for Men', category: 'Fashion', price: 1299, originalPrice: 2499, rating: 4.6, reviews: 3210, badge: 'Bestseller', img: 'wallet', featured: true, trending: false, bestseller: true, flashdeal: false, desc: 'Handcrafted genuine leather wallet with RFID blocking technology. Features 6 card slots, two currency compartments, and a secure coin pocket.', specs: { Material: 'Genuine Leather', Cards: '6 slots', RFID: 'Yes', Color: 'Brown' } },
  { id: 4, name: 'Portable Bluetooth Speaker Waterproof', category: 'Electronics', price: 1799, originalPrice: 3499, rating: 4.4, reviews: 4521, badge: 'Trending', img: 'speaker', featured: true, trending: true, bestseller: false, flashdeal: true, desc: 'Rugged IP67 waterproof Bluetooth speaker with 360-degree surround sound, 20-hour battery life, and built-in microphone for calls.', specs: { Brand: 'BoomBox', Battery: '20h', Water: 'IP67', Output: '30W' } },
  { id: 5, name: "Men's Classic Fit Casual Shirt", category: 'Fashion', price: 899, originalPrice: 1999, rating: 4.2, reviews: 5678, badge: null, img: 'casual-shirt', featured: true, trending: false, bestseller: false, flashdeal: false, desc: 'Premium cotton casual shirt with a classic button-down collar, chest pocket, and adjustable cuffs. Machine washable and wrinkle-resistant.', specs: { Material: '100% Cotton', Fit: 'Classic', Sizes: 'S-3XL', Origin: 'India' } },
  { id: 6, name: 'Professional DSLR Camera 24MP', category: 'Electronics', price: 45999, originalPrice: 59999, rating: 4.7, reviews: 1234, badge: null, img: 'dslr-camera', featured: false, trending: true, bestseller: false, flashdeal: false, desc: 'High-performance 24.2MP DSLR camera with 4K UHD video recording, advanced 45-point autofocus system, and 18-55mm kit lens.', specs: { Brand: 'PhotoMax', 'MP': '24.2MP', Video: '4K UHD', Weight: '650g' } },
  { id: 7, name: 'Running Shoes Ultra Comfort', category: 'Sports', price: 2999, originalPrice: 5999, rating: 4.5, reviews: 8765, badge: 'Popular', img: 'running-shoes', featured: true, trending: true, bestseller: true, flashdeal: true, desc: 'Lightweight running shoes with responsive cloud-like cushioning and breathable mesh upper. Designed for maximum comfort during long-distance runs.', specs: { Brand: 'RunFast', Sole: 'Rubber', Weight: '280g', Sizes: '6-12 UK' } },
  { id: 8, name: 'Smart Watch Pro with AMOLED Display', category: 'Electronics', price: 5999, originalPrice: 9999, rating: 4.4, reviews: 3456, badge: null, img: 'smart-watch', featured: true, trending: true, bestseller: true, flashdeal: false, desc: 'Premium smartwatch featuring a 1.43-inch AMOLED display, built-in GPS, 100+ workout modes, blood oxygen monitoring, and 7-day battery life.', specs: { Brand: 'TechWear', Display: '1.43" AMOLED', Battery: '7 days', GPS: 'Built-in' } },
  { id: 9, name: 'Wireless Earbuds with Charging Case', category: 'Electronics', price: 1499, originalPrice: 2999, rating: 4.3, reviews: 6789, badge: 'New', img: 'earbuds', featured: true, trending: true, bestseller: false, flashdeal: true, desc: 'True wireless earbuds with active noise cancellation, intuitive touch controls, and 24-hour total battery life with the compact charging case.', specs: { Brand: 'SoundMax', Battery: '24h', Bluetooth: '5.3', Drivers: '13mm' } },
  { id: 10, name: 'Designer Leather Handbag for Women', category: 'Fashion', price: 3499, originalPrice: 6999, rating: 4.7, reviews: 2341, badge: 'Premium', img: 'handbag', featured: true, trending: false, bestseller: true, flashdeal: false, desc: 'Elegant genuine leather handbag with gold-toned hardware. Features multiple compartments, a detachable shoulder strap, and a secure top zip closure.', specs: { Material: 'Genuine Leather', Hardware: 'Gold', Origin: 'Italy' } },
  { id: 11, name: 'Stainless Steel Water Bottle 1L', category: 'Home', price: 799, originalPrice: 1499, rating: 4.6, reviews: 9876, badge: 'Eco', img: 'water-bottle', featured: true, trending: false, bestseller: true, flashdeal: false, desc: 'Double-wall vacuum insulated water bottle that keeps drinks cold for 24 hours or hot for 12 hours. 100% BPA-free and leak-proof.', specs: { Brand: 'EcoSip', Capacity: '1L', 'Cold': '24h', 'Hot': '12h' } },
  { id: 12, name: 'Organic Green Tea Collection', category: 'Grocery', price: 499, originalPrice: 899, rating: 4.4, reviews: 5432, badge: null, img: 'green-tea', featured: true, trending: false, bestseller: false, flashdeal: false, desc: 'Premium organic green tea gift set with three exquisite varieties: Japanese Sencha, Jasmine Green, and Mint Green. 100 biodegradable tea bags.', specs: { Brand: 'Nature\'s Brew', Bags: '100', Organic: 'Yes' } },
  { id: 13, name: 'Gaming Mouse RGB Backlit', category: 'Electronics', price: 1199, originalPrice: 2499, rating: 4.3, reviews: 3210, badge: null, img: 'gaming-mouse', featured: false, trending: true, bestseller: false, flashdeal: false, desc: 'Ergonomic gaming mouse with 6 programmable buttons, adjustable 3200 DPI sensor, and customizable RGB lighting effects.', specs: { Brand: 'GameMax', DPI: '3200', Buttons: '6', RGB: 'Yes' } },
  { id: 14, name: 'Men\'s Slim Fit Blazer', category: 'Fashion', price: 2499, originalPrice: 4999, rating: 4.1, reviews: 1876, badge: 'Sale', img: 'blazer', featured: false, trending: false, bestseller: false, flashdeal: false, desc: 'Sharp slim-fit blazer crafted from premium polyester blend fabric. Perfect for formal occasions, business meetings, and evening events.', specs: { Material: 'Polyester Blend', Fit: 'Slim', Sizes: 'S-3XL' } },
  { id: 15, name: 'Yoga Mat Premium Non-Slip', category: 'Sports', price: 999, originalPrice: 1999, rating: 4.5, reviews: 6543, badge: 'Bestseller', img: 'yoga-mat', featured: false, trending: true, bestseller: true, flashdeal: false, desc: 'Extra thick 6mm yoga mat made from eco-friendly TPE material. Dual-sided non-slip surface provides excellent grip during any workout.', specs: { Brand: 'FlexFit', Thickness: '6mm', Material: 'TPE Eco' } },
  { id: 16, name: 'Smart Home Security Camera', category: 'Electronics', price: 2999, originalPrice: 4999, rating: 4.2, reviews: 2109, badge: null, img: 'security-camera', featured: false, trending: false, bestseller: false, flashdeal: true, desc: '1080p wireless security camera with night vision, motion detection alerts, two-way audio, and cloud storage. Works with Alexa and Google Home.', specs: { Brand: 'SecureView', Resolution: '1080p', 'Night Vision': 'Yes', Wireless: 'Yes' } },
  { id: 17, name: 'Women\'s Cotton Summer Dress', category: 'Fashion', price: 1399, originalPrice: 2799, rating: 4.4, reviews: 4321, badge: null, img: 'summer-dress', featured: false, trending: true, bestseller: false, flashdeal: false, desc: 'Lightweight and breathable cotton sundress with a charming floral print. Features an A-line cut, adjustable waist tie, and knee-length hem.', specs: { Material: '100% Cotton', Length: 'Knee', Sizes: 'XS-XL' } },
  { id: 18, name: 'Protein Powder Whey Isolate 1kg', category: 'Sports', price: 1999, originalPrice: 3499, rating: 4.6, reviews: 7890, badge: 'Popular', img: 'protein-powder', featured: false, trending: false, bestseller: true, flashdeal: true, desc: 'Pure whey protein isolate with 25g of protein per serving. Zero added sugar, mixable instantly, and delicious chocolate flavor.', specs: { Brand: 'FitFuel', Protein: '25g/serving', Weight: '1kg', Flavor: 'Chocolate' } },
  { id: 19, name: 'Mechanical Keyboard RGB Cherry MX', category: 'Electronics', price: 4499, originalPrice: 6999, rating: 4.5, reviews: 1567, badge: null, img: 'mechanical-keyboard', featured: false, trending: false, bestseller: false, flashdeal: false, desc: 'Full-size mechanical keyboard with genuine Cherry MX Blue switches for satisfying tactile feedback. Per-key RGB backlighting with customizable effects.', specs: { Brand: 'TypeMaster', Switches: 'Cherry MX Blue', Layout: 'Full-size', RGB: 'Per-key' } },
  { id: 20, name: 'Aromatherapy Essential Oil Diffuser', category: 'Home', price: 1299, originalPrice: 2499, rating: 4.3, reviews: 3456, badge: null, img: 'oil-diffuser', featured: false, trending: false, bestseller: false, flashdeal: false, desc: 'Ultrasonic essential oil diffuser with a 300ml capacity, 7-color LED mood lighting, and automatic shut-off timer. Runs whisper-quiet for up to 8 hours.', specs: { Brand: 'AromaGlow', Capacity: '300ml', 'LED Colors': '7', 'Auto Shutoff': 'Yes' } },
  { id: 21, name: 'Men\'s Analog Watch Premium', category: 'Fashion', price: 3999, originalPrice: 7999, rating: 4.4, reviews: 2345, badge: 'Sale', img: 'analog-watch', featured: false, trending: true, bestseller: false, flashdeal: false, desc: 'Sophisticated analog watch with a premium stainless steel strap, scratch-resistant mineral glass, chronograph movement, and 50m water resistance.', specs: { Brand: 'TimeCraft', Movement: 'Quartz', Strap: 'Stainless Steel', 'Water': '50m' } },
  { id: 22, name: 'Portable Power Bank 20000mAh', category: 'Electronics', price: 1499, originalPrice: 2999, rating: 4.4, reviews: 8901, badge: null, img: 'power-bank', featured: false, trending: false, bestseller: true, flashdeal: true, desc: 'High-capacity 20000mAh portable charger with dual USB output ports and fast charging support. Charges smartphones up to 6 times on a single charge.', specs: { Brand: 'PowerMax', Capacity: '20000mAh', Ports: '2 USB', 'Fast Charge': 'Yes' } },
  { id: 23, name: 'Natural Bamboo Cutting Board Set', category: 'Home', price: 699, originalPrice: 1399, rating: 4.5, reviews: 4567, badge: 'Eco', img: 'cutting-board', featured: false, trending: false, bestseller: false, flashdeal: false, desc: 'Set of 3 organic bamboo cutting boards in graduated sizes. Naturally antimicrobial, knife-friendly surface with easy-grip handles and juice grooves.', specs: { Material: 'Organic Bamboo', Pieces: '3', Sizes: 'S/M/L' } },
  { id: 24, name: 'Wireless Charging Pad Fast', category: 'Electronics', price: 999, originalPrice: 1999, rating: 4.2, reviews: 6543, badge: null, img: 'wireless-charger', featured: false, trending: false, bestseller: false, flashdeal: false, desc: '15W fast wireless charging pad compatible with all Qi-enabled devices. Slim design with LED indicator and foreign object detection.', specs: { Brand: 'ChargePro', Speed: '15W', Standard: 'Qi', LED: 'Yes' } },
  { id: 25, name: 'Resistance Bands Set for Home Gym', category: 'Sports', price: 599, originalPrice: 1299, rating: 4.3, reviews: 10987, badge: 'Bestseller', img: 'resistance-bands', featured: false, trending: false, bestseller: true, flashdeal: false, desc: 'Complete set of 5 resistance bands with varying tension levels from light to extra-heavy. Includes door anchor, ankle straps, and carry bag.', specs: { Pieces: '5', Levels: 'Light-X-Heavy', Material: 'Natural Latex' } },
  { id: 26, name: 'Air Purifier with HEPA Filter', category: 'Home', price: 7999, originalPrice: 12999, rating: 4.4, reviews: 1234, badge: null, img: 'air-purifier', featured: false, trending: false, bestseller: false, flashdeal: false, desc: 'True HEPA air purifier covering rooms up to 300 square feet. Captures 99.97% of airborne particles. Ultra-quiet operation at just 25 decibels.', specs: { Brand: 'PureAir', 'Room Size': '300 sq ft', Filter: 'True HEPA', Noise: '25dB' } },
  { id: 27, name: 'Leather Sneakers Casual', category: 'Fashion', price: 2199, originalPrice: 4499, rating: 4.3, reviews: 3456, badge: null, img: 'sneakers', featured: false, trending: false, bestseller: false, flashdeal: false, desc: 'Premium genuine leather sneakers with a cushioned EVA sole for all-day comfort. Versatile design pairs perfectly with jeans or chinos.', specs: { Material: 'Genuine Leather', Sole: 'Rubber', Sizes: '7-11 UK' } },
  { id: 28, name: 'Bluetooth Car FM Transmitter', category: 'Electronics', price: 699, originalPrice: 1499, rating: 4.1, reviews: 5432, badge: null, img: 'car-fm-transmitter', featured: false, trending: false, bestseller: false, flashdeal: false, desc: 'Bluetooth 5.0 car FM transmitter with hands-free calling, music streaming, and dual USB charging ports. LED display shows frequency and caller ID.', specs: { Brand: 'DriveSync', Bluetooth: '5.0', Ports: '2 USB' } },
  { id: 29, name: 'Meditation Cushion Floor Pillow', category: 'Home', price: 1599, originalPrice: 2999, rating: 4.5, reviews: 2345, badge: null, img: 'meditation-cushion', featured: false, trending: false, bestseller: false, flashdeal: false, desc: 'Buckwheat-filled meditation cushion with a removable organic cotton cover. Ergonomically designed to support proper posture during meditation.', specs: { Material: 'Organic Cotton', Fill: 'Buckwheat', Height: '6"' } },
  { id: 30, name: 'Men\'s Grooming Kit 12-Piece', category: 'Grocery', price: 849, originalPrice: 1699, rating: 4.2, reviews: 4567, badge: null, img: 'grooming-kit', featured: false, trending: false, bestseller: false, flashdeal: false, desc: 'Complete 12-piece grooming kit featuring a precision trimmer, detail clippers, styling scissors, combs, and travel case. Cordless with 4-hour battery.', specs: { Pieces: '12', Brand: 'GroomPro', 'Battery Life': '4h' } },
  { id: 31, name: 'Kids Building Blocks 500-Piece', category: 'Toys', price: 1299, originalPrice: 2499, rating: 4.6, reviews: 8901, badge: null, img: 'building-blocks', featured: false, trending: false, bestseller: true, flashdeal: false, desc: 'Colorful 500-piece building blocks set in a reusable storage box. Made from non-toxic ABS plastic. Compatible with all major building block brands.', specs: { Pieces: '500', Material: 'Non-toxic ABS', Age: '3+' } },
  { id: 32, name: 'Noise Cancelling Sleep Earplugs', category: 'Beauty', price: 499, originalPrice: 999, rating: 4.3, reviews: 6543, badge: null, img: 'earplugs', featured: false, trending: false, bestseller: false, flashdeal: false, desc: 'Reusable medical-grade silicone earplugs that reduce noise by 32dB. Comfortable for all-night wear. Includes a portable carrying case.', specs: { Material: 'Medical-grade Silicone', 'Noise Reduction': '32dB', Reusable: 'Yes' } },
  { id: 33, name: 'The Great Gatsby - Classic Fiction Novel', category: 'Books', price: 299, originalPrice: 599, rating: 4.7, reviews: 12345, badge: 'Bestseller', img: 'book', featured: true, trending: true, bestseller: true, flashdeal: false, desc: 'F. Scott Fitzgerald\'s timeless masterpiece about the American Dream. This beautifully bound edition features an exclusive introduction and discussion questions.', specs: { Author: 'F. Scott Fitzgerald', Pages: '208', Publisher: 'Classic Press', Format: 'Hardcover' } },
  { id: 34, name: 'Atomic Habits - Build Good Habits Fast', category: 'Books', price: 499, originalPrice: 999, rating: 4.8, reviews: 23456, badge: '#1 Best Seller', img: 'book', featured: true, trending: true, bestseller: true, flashdeal: false, desc: 'James Clear\'s revolutionary guide to breaking bad behaviors and adopting good ones. Learn the science of habit formation with practical strategies.', specs: { Author: 'James Clear', Pages: '320', Publisher: 'Penguin', Format: 'Paperback' } },
  { id: 35, name: 'Python Programming for Beginners', category: 'Books', price: 699, originalPrice: 1299, rating: 4.5, reviews: 8765, badge: 'New', img: 'book', featured: false, trending: true, bestseller: false, flashdeal: false, desc: 'The ultimate beginner-friendly guide to Python programming. Packed with practical projects, clear explanations, and hands-on exercises.', specs: { Author: 'Alex Miller', Pages: '450', Publisher: 'TechPress', Format: 'Paperback' } },
];

const Categories = [
  { name: 'Electronics', icon: '\u26A1' },
  { name: 'Fashion', icon: '\uD83D\uDC55' },
  { name: 'Sports', icon: '\u26BD' },
  { name: 'Home', icon: '\uD83C\uDFE0' },
  { name: 'Beauty', icon: '\uD83D\uDC84' },
  { name: 'Grocery', icon: '\uD83C\uDF4E' },
  { name: 'Toys', icon: '\uD83E\uDEE1' },
  { name: 'Books', icon: '\uD83D\uDCDA' },
];

const Reviews = [
  { name: 'Priya Sharma', avatar: 'rev1', text: 'Absolutely love my purchase! The quality exceeded my expectations. Fast delivery and excellent packaging. Will definitely shop again!', rating: 5 },
  { name: 'Rahul Verma', avatar: 'rev2', text: 'Great experience shopping at VCart. The product is exactly as described. Customer service was very helpful with my queries.', rating: 5 },
  { name: 'Ananya Gupta', avatar: 'rev3', text: 'Best online shopping experience! The prices are competitive and the quality is top-notch. Highly recommend to everyone.', rating: 5 },
  { name: 'Vikram Singh', avatar: 'rev4', text: 'I was hesitant to order online but VCart made it so easy. The product arrived on time and in perfect condition.', rating: 4 },
  { name: 'Neha Patel', avatar: 'rev5', text: 'From ordering to delivery, everything was seamless. The product quality is amazing. My new go-to shopping destination.', rating: 5 },
  { name: 'Arjun Kumar', avatar: 'rev6', text: 'Outstanding customer service! Had an issue with my order and they resolved it within hours. Very impressed.', rating: 5 },
];

const Brands = ['Samsung', 'Apple', 'Sony', 'LG', 'Boat', 'Puma', 'Nike', 'Adidas', 'Dell', 'HP', 'OnePlus', 'Lenovo'];
